#! /bin/bash

if [[ -f bookshelfActive2 ]]
then
    rm cart.csv
fi

cart_id=1
while IFS= read -r  line
do
	iduser=$(echo $line | awk -F"|" '{print $1}')
	date=$(bash ./rand_dates.sh 1 1 2020 2022)
	psql -d fdd2db -c "SELECT book_id, percentil FROM percentil order by RANDOM() limit $(((RANDOM%10)+1))" | sed '1d' | sed '1d' | sed 's| ||g' | head -n -2 | sed "s/^/|$iduser|/g" | sed "s/$/|$date/g" | sed "s/^/$cart_id/g" >> cart.csv
	cart_id=$((cart_id + 1))
done < user.csv

# ----------------------------------------
# Crear tabla 'cart'
# ----------------------------------------

echo "Creating table cart"
psql -d fdd2db -c "create table if not exists cart (cart_id serial primary key, user_id integer, product_id integer, percentil integer, purchase_date date)"
#Borrado los datos anteriores de la tabla
psql -d fdd2db -c "TRUNCATE cart"

# ----------------------------------------
# Insertar datos de un archivo csv
# ----------------------------------------

echo "Populating table cart"
psql -d fdd2db -c "\copy cart from 'cart.csv' delimiter '|'"
psql -d fdd2db -c "select * from cart"
